### PR TITLE
Breakpoints support and launch.json parameters

### PR DESCRIPTION
**Pull request by mitsakosgr**
Add more languages to support more dialects to vscode

Add parameters to launch.json
- "freeSourceFormat": boolean to allow disabling free format
- "dialect": string to change cobol dialect
- "cobcArgs": stirng to add more parameters to compiler

### CODE REVIEW

**Comment by mitsakosgr** [comment]
Fixes #6 and partial requests from #10

**Comment by GitMensch** [comment]
Thank you, fix looks good! I'd immediately pull :-)
I see the fix for #6 is in the "contributes" part of package.json, interesting to know and much better than the ugly workaround with switching to C# :-)

Can I ask you to integrate a toggle for "-fdebugging-line" [compile all debugging lines] and "-d" [activate all runtime checks] as this would fix everything from #10 that is only compile-related (the "main" part and the arguments for main both needs adjustments in the starting programs, still reasonable but likely worth a different PR).

Side note: package.json "looks" to be completely replaced (EOL, tabsVSspace issue?).

**Comment by mitsakosgr** [comment]
I last edited package.json in windows and forgot CRLF as line ending. That's why it shows up as changed. I force pushed it to change to LF.

You can still add -d in cobcArgs. It is not visible right away, but you can add it in launch.json.

**Comment by GitMensch** [comment]
> You can still add -d in cobcArgs. It is not visible right away, but you can add it in launch.json.

No, it is not possible as both `-g` and `-fdebugging-line` are {currently forced](https://github.com/OlegKunitsyn/gnucobol-debug/pull/11/files#diff-1495585c9a344bbfa848190a8db013e8R79) - as it is nearly identical to your changes and would solve everything that is only compile-time-related from #10 I've asked you to add those two.

**Comment by GitMensch** [comment]
@OlegKunitsyn Is there a reason that you did not merged this PR (here)?
In any case: it would be good to close it, possibly after adding a toggle for ` -d` and `-fdebugging-line`, to be able to also close #10.

**Comment by OlegKunitsyn** [comment]
please check 0.8.22

**Comment by gfmoore** [comment]
regards,

Gordon
gm@gordonmoore.co.uk

On 24/04/2020 15:58:21, OlegKunitsyn <notifications@github.com> wrote:
please check 0.8.22

**Comment by gfmoore** [comment]
reverted back to 0.6.2 and ok again

regards,

Gordon
gm@gordonmoore.co.uk

On 24/04/2020 15:58:21, OlegKunitsyn <notifications@github.com> wrote:
please check 0.8.22

**Comment by GitMensch** [comment]
@gfmoore  Why did you reverted from 0.8.22?

**Comment by gfmoore** [comment]
er, because it failed!

I did reply, but here it is again

working 0.6.22

not working 0.8.22


regards,

Gordon
gm@gordonmoore.co.uk

On 24/04/2020 17:32:53, Simon Sobisch <notifications@github.com> wrote:
@gfmoore [https://github.com/gfmoore] Why did you reverted from 0.8.22?

**Comment by mitsakosgr** [comment]
Remove launch.json and recreate it. It needs extra parameters for 0.8.22

**Comment by gfmoore** [comment]
okay. Managed to do that (eventually) and now compiling again - thanks!

regards,

Gordon
gm@gordonmoore.co.uk

On 24/04/2020 18:34:42, Dimitris Pappas <notifications@github.com> wrote:
Remove launch.json and recreate it. It needs extra parameters for 0.8.22

**Comment by gfmoore** [comment]
hey big :) and now the breakpoint is working - you can close that issue (or do I do it?) Coolio.

regards,

Gordon
gm@gordonmoore.co.uk

On 24/04/2020 18:34:42, Dimitris Pappas <notifications@github.com> wrote:
Remove launch.json and recreate it. It needs extra parameters for 0.8.22

**Comment by OlegKunitsyn** [comment]
I'm sorry for the inconvenience and late reply. As long as the extension is beta and number of installs < 100, re-creation of launch.json might be necessary. In other words, it's too early to deal with backward compatibility. Thank you for the pull request and your contribution, gentlemen.

**Pull request closed without merging**
