### PR TITLE
fail to launch COBOL debugger #29

### PR DESCRIPTION
**Pull request by l-github-245**
Hi, I can run gdb against cbl sources in win10, using Trembley's packages, which now include PDCursesMod 4.2.0, btw. I do not use dockers / linux for cobol development so I cannot guarantee it will not break anything else, unfortunately.

### CODE REVIEW

**Comment by OlegKunitsyn** [comment]
@mayhd3 can you check updated `nativePath` on Windows Docker setup please?

**Comment by mayhd3** [comment]
GDB always started to run in the container when I tested it, but it still runs into path errors. To get it to start running on this branch, I had to change line 91 of `mi2.ts` to `target = nativePath.resolve(cwd, target).replace(/.*:/, s => "/" + s.toLowerCase().replace(":", "")).replace(/\\/g, "/");`. After this, the relevant gdb errors in the debug console were:

```
stdout: &"Warning: /d/Documents/GitHub/stele/CSC310HW1/D:\\Documents\\GitHub\\stele\\CSC310HW1: No such file or directory.\n"
5^done,source-path="/d/Documents/GitHub/stele/CSC310HW1/D:\\Documents\\GitHub\\stele\\CSC310HW1:$cdir:$cwd"
(gdb) 
GDB -> App: {"outOfBandRecord":[{"isStream":true,"type":"log","content":"Warning: /d/Documents/GitHub/stele/CSC310HW1/D:\\Documents\\GitHub\\stele\\CSC310HW1: No such file or directory.\n"}]}
Warning: /d/Documents/GitHub/stele/CSC310HW1/D:\Documents\GitHub\stele\CSC310HW1: No such file or directory.
GDB -> App: {"token":5,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["source-path","/d/Documents/GitHub/stele/CSC310HW1/D:\\Documents\\GitHub\\stele\\CSC310HW1:$cdir:$cwd"]]}}
stdout: 6^error,msg="D:\\Documents\\GitHub\\stele\\CSC310HW1\\homework: No such file or directory."
(gdb) 
```

So it seems somehow the incorrect path is sometimes appended to the correct path, but I cannot find where or how this happens 😢 

This branch did not cause this problem though, my fork was only to let me run `cobc` without debugging. I never fixed gdb because I only needed to complete one project, and I still do not know what to do about the mix of windows and unix style paths here. Anything vscode uses needs to be a windows path on windows, but anything the container uses needs to be a unix path on windows. Thank you for your extension, I would prefer to be running linux anyways so these issues were not terrible for me.

**Comment by mayhd3** [comment]
also if I use GNUCobol more in the future I plan on using @l-github-245 's setup, docker uses too much memory for my laptop anyways.

**Comment by OlegKunitsyn** [comment]
@mayhd3 thanks for input, I'll merge and update readme. We still need a Win10 hero :)

**Pull request merged**
