### PR TITLE
Feature #40 - support for setting values

### PR DESCRIPTION
**Pull request by brunopacheco1**
The current PR includes the following changes:
- Support for setting data storages values on GC 2.2+;
- Support for setting field values on GC 2.2 (display values only);

### CODE REVIEW

**Comment by OlegKunitsyn** [comment]
Breakpoints fail 

>Failed to set value on hello_.b_2
Not supported type: integer

>Failed to set value on petstore_.b_2
Not supported type: integer

**Comment by GitMensch** [comment]
@brunopacheco1 GC2.2+? Did you mean GC3.1rc1+?
Question: Did anybody tried this with GC 1.1 (_should_ be nearly identical to the code generation of OpenCOBOL 1.1; both are still used in some repos) and/or [opensource COBOL](https://github.com/opensourcecobol/opensource-cobol) which is based on OC 1.1?

**Comment by brunopacheco1** [comment]
Yes, you are right, I was thinking on GC 3.1 rc1+. I didn't try on lower versions.

**Comment by brunopacheco1** [comment]
> Breakpoints fail
> 
> > Failed to set value on hello_.b_2
> > Not supported type: integer
> 
> > Failed to set value on petstore_.b_2
> > Not supported type: integer

I am opening a new issue to track this one, as it requires some discussion on that.

**Comment by GitMensch** [comment]
> Yes, you are right, I was thinking on GC 3.1 rc1+. I didn't try on lower versions.

The feature to set variables is missing in the README for this PR to be complete (sorry to have missed that before).

**Comment by brunopacheco1** [comment]
> The feature to set variables is missing in the README for this PR to be complete (sorry to have missed that before).

I didn't update the README, because I was waiting for you or Oleg to review it.

**Pull request merged**
