### PR TITLE
Bugfix #79 - Support for setting RETURN-CODE value

### PR DESCRIPTION
**Pull request by brunopacheco1**
As RETURN-CODE is neither data storage nor a field, the extension wasn't setting correctly its value.

For now, to fix this problem, a third flow for setting variable values was created just for integer typed variables (first flow is when the GC has the function `cob_set_field_str()` and the second flow is used when there is no function, but supports only display values);

@GitMensch is there any other variable in a similar situation? If yes, the extension should support it as well and the current solution is partially covering this problem.

### CODE REVIEW

**Comment by GitMensch** [comment]
Can you please add a testcase entry? (I try to learn how this extension work to possibly create useful PR in the future...)

**Comment by brunopacheco1** [comment]
> Can you please add a testcase entry? (I try to learn how this extension work to possibly create useful PR in the future...)

I really would like to have test cases on MI2 class.

**Comment by GitMensch** [comment]
> is there any other variable in a similar situation?

that likely applies to other registers, too. `SORT-RETURN` for example. In the meantime I've found a read-only "register": `WHEN-COMPILED`. Applying `cob_put_field_str` should result in `EINVAL` and a runtime warning (if not globally disabled) of "attempt to over-write constant field with ...".
Note: this can be pre-checked with `int cob_get_field_constant (cob_field *)` which returns -1 (called with `NULL`), 0 (not a constant) or 1 (specified field is a constant).

**Comment by GitMensch** [comment]
> I really would like to have test cases on MI2 class.

If there aren't any: please create an issue for this to ensure it is added sooner than later and to gather any information that is relevant (and to have a nice reference to add to the ChangeLog).

**Pull request merged**
