### PR TITLE
Fields

### PR DESCRIPTION
**Pull request by GitMensch**
Seems the latest changes are missing. I suggest to pull the branch in and create a new release from the new master.

### CODE REVIEW

**Comment by GitMensch** [comment]
@brunopacheco1 Do you have any idea why the test fails? [this PR may be completely non-sense then it should be replaced by something reasonable]

**Comment by OlegKunitsyn** [comment]
> @brunopacheco1 Do you have any idea why the test fails? [this PR may be completely non-sense then it should be replaced by something reasonable]

Can't reproduce locally. The action has been disabled.

**Comment by brunopacheco1** [comment]
> @brunopacheco1 Do you have any idea why the test fails? [this PR may be completely non-sense then it should be replaced by something reasonable]

I am checking here and there are three tests failing.

`
1) Gcov
       Hello:

      AssertionError [ERR_ASSERTION]: '33,true' == '33,false'
      + expected - actual

      -33,true
      +33,false
      
      at Context.test (out/test/gcov.test.js:18:20)

  2) Gcov
       Sample:

      AssertionError [ERR_ASSERTION]: '38,true' == '38,false'
      + expected - actual

      -38,true
      +38,false
      
      at Context.test (out/test/gcov.test.js:34:20)

  3) C code parse
       Minimal:

      AssertionError [ERR_ASSERTION]: 105 == 0
      + expected - actual

      -105
      +0
      
      at Context.test (out/test/parser.c.test.js:16:16)
`
The last failure is a problem with an absolute folder reference, explicitly written down on line 2, file "test/resources/hello.c". To fix it the parser should get only the file name (without path) and let cwd provide the full path.

The first two tests I am not sure, perhaps @OlegKunitsyn have a better understanding of GCOV. I would guess it is a similar path/env problem, as these 3 tests are working on his machine, but not outside.

**Comment by brunopacheco1** [comment]
I pushed on fields a fix for the last failing test and some minor changes to improve verbose mode;

**Comment by OlegKunitsyn** [comment]
Tests are green, the changes were merged into masted. 
Thank you @brunopacheco1 !

**Pull request merged**
